spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

file:
  upload-dir: ${PHOTO_PATH}

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

verification:
  mail:
    baseurl: https://petshelter-production.up.railway.app/

  resend:
    api:
      key: ${VERIFICATION_RESEND_API_KEY}