spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

file:
  upload-dir: ${PHOTO_PATH}

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

verification:
  mail:
    verify-email-url: https://project-pet-shelter-new.netlify.app/verify-email?token=
    verify-password-reset: https://project-pet-shelter-new.netlify.app/verify-reset?token=

  resend:
    api:
      key: ${VERIFICATION_RESEND_API_KEY}

#
#  spring.mail.host=smtp.prod.example.com
#  spring.mail.port=587