package ua.tc.marketplace.model.enums;

import static org.springframework.http.HttpMethod.*;
import static org.springframework.http.HttpMethod.GET;
import static ua.tc.marketplace.config.ApiURLs.*;
import static ua.tc.marketplace.model.enums.AccessPolicy.*;

import lombok.Getter;
import org.springframework.http.HttpMethod;

@Getter
public enum ApiEndpoint {

  // Ad
  AD_GET_ALL_ENDPOINT(AD_BASE + AD_GET_ALL, GET, PUBLIC),
  AD_GET_ALL_COUNTED_ENDPOINT(AD_BASE + AD_GET_ALL_COUNTED, GET, PUBLIC),
  AD_GET_BY_ID_ENDPOINT(AD_BASE + AD_GET_BY_ID, GET, PUBLIC),
  AD_CREATE_ENDPOINT(AD_BASE + AD_CREATE, POST, AUTHENTICATED),
  AD_UPDATE_ENDPOINT(AD_BASE + AD_UPDATE, PUT, AUTHENTICATED_AND_OWNER),
  AD_DELETE_ENDPOINT(AD_BASE + AD_DELETE, DELETE, ADMIN_OR_AUTHENTICATED_AND_OWNER),

  // Article
  ARTICLE_GET_ALL_ENDPOINT(ARTICLE_BASE + ARTICLE_GET_ALL, GET, PUBLIC),
  ARTICLE_GET_BY_ID_ENDPOINT(ARTICLE_BASE + ARTICLE_GET_BY_ID, GET, PUBLIC),
  ARTICLE_CREATE_ENDPOINT(ARTICLE_BASE + ARTICLE_CREATE, POST, AUTHENTICATED),
  ARTICLE_UPDATE_ENDPOINT(ARTICLE_BASE + ARTICLE_UPDATE, PUT, AUTHENTICATED_AND_OWNER),
  ARTICLE_DELETE_ENDPOINT(ARTICLE_BASE + ARTICLE_DELETE, DELETE, ADMIN_OR_AUTHENTICATED_AND_OWNER),

  // Attribute
  ATTRIBUTE_GET_ALL_ENDPOINT(ATTRIBUTE_BASE + ATTRIBUTE_GET_ALL, GET, PUBLIC),
  ATTRIBUTE_GET_BY_ID_ENDPOINT(ATTRIBUTE_BASE + ATTRIBUTE_GET_BY_ID, GET, PUBLIC),
  ATTRIBUTE_CREATE_ENDPOINT(ATTRIBUTE_BASE + ATTRIBUTE_CREATE, POST, AUTHENTICATED),
  ATTRIBUTE_UPDATE_ENDPOINT(ATTRIBUTE_BASE + ATTRIBUTE_UPDATE, PUT, AUTHENTICATED_AND_OWNER),
  ATTRIBUTE_DELETE_ENDPOINT(ATTRIBUTE_BASE + ATTRIBUTE_DELETE, DELETE, ADMIN_OR_AUTHENTICATED_AND_OWNER),

  // Auth
  AUTH_LOGIN_ENDPOINT(AUTH_BASE + AUTH_LOGIN, POST, PUBLIC),
  AUTH_SIGNUP_ENDPOINT(AUTH_BASE + AUTH_SIGNUP, POST, PUBLIC),
  AUTH_VERIFY_EMAIL_ENDPOINT(AUTH_BASE + AUTH_VERIFY_EMAIL, POST, PUBLIC),
  AUTH_VERIFY_EMAIL_LOGIN_ENDPOINT(AUTH_BASE + AUTH_VERIFY_EMAIL_LOGIN, POST, PUBLIC),
  AUTH_VERIFY_EMAIL_WITH_TOKEN_ENDPOINT(AUTH_BASE + AUTH_VERIFY_EMAIL_WITH_TOKEN, GET, PUBLIC),
  AUTH_FORGET_PASSWORD_ENDPOINT(AUTH_BASE + AUTH_FORGET_PASSWORD, POST, PUBLIC),
  AUTH_VERIFY_PASSWORD_RESET_ENDPOINT(AUTH_BASE + AUTH_VERIFY_PASSWORD_RESET, POST, PUBLIC),
  AUTH_VERIFY_PASSWORD_RESET_WITH_TOKEN_ENDPOINT(AUTH_BASE + AUTH_VERIFY_PASSWORD_RESET_WITH_TOKEN, GET, PUBLIC),
  AUTH_RESET_PASSWORD_ENDPOINT(AUTH_BASE + AUTH_RESET_PASSWORD, POST, PUBLIC),
  AUTH_SIGNUP_WITH_VERIFY_ENDPOINT(AUTH_BASE + AUTH_SIGNUP_WITH_VERIFY, POST, PUBLIC),
  AUTH_LIST_TOKENS_ENDPOINT(AUTH_BASE + LIST_TOKENS, GET, AUTHENTICATED),

  // Category
  CATEGORY_GET_ALL_ENDPOINT(CATEGORY_BASE + CATEGORY_GET_ALL, GET, PUBLIC),
  CATEGORY_GET_ALL_COUNTED_ENDPOINT(CATEGORY_BASE + CATEGORY_GET_ALL_COUNTED, GET, PUBLIC),
  CATEGORY_BY_ID_ENDPOINT(CATEGORY_BASE + CATEGORY_BY_ID, GET, PUBLIC),
  CATEGORY_ATTRIBUTE_BY_IDS_ENDPOINT(CATEGORY_BASE + CATEGORY_ATTRIBUTE_BY_IDS, GET, PUBLIC),
  CATEGORY_ATTRIBUTES_BY_CATEGORY_ID_ENDPOINT(CATEGORY_BASE + CATEGORY_ATTRIBUTES_BY_CATEGORY_ID, GET, PUBLIC),
  CATEGORY_CREATE_ENDPOINT(CATEGORY_BASE + CATEGORY_CREATE, POST, AUTHENTICATED),
  CATEGORY_UPDATE_ENDPOINT(CATEGORY_BASE + CATEGORY_UPDATE, PUT, AUTHENTICATED_AND_OWNER),
  CATEGORY_ATTRIBUTE_UPDATE_ENDPOINT(CATEGORY_BASE + CATEGORY_ATTRIBUTE_UPDATE, PUT, AUTHENTICATED_AND_OWNER),
  CATEGORY_DELETE_ENDPOINT(CATEGORY_BASE + CATEGORY_DELETE, DELETE, ADMIN_OR_AUTHENTICATED_AND_OWNER),

  // Comment
  COMMENT_GET_ALL_ENDPOINT(COMMENT_BASE + COMMENT_GET_ALL, GET, PUBLIC),
  COMMENT_GET_BY_ID_ENDPOINT(COMMENT_BASE + COMMENT_GET_BY_ID, GET, PUBLIC),
  COMMENT_CREATE_ENDPOINT(COMMENT_BASE + COMMENT_CREATE, POST, AUTHENTICATED),
  COMMENT_UPDATE_ENDPOINT(COMMENT_BASE + COMMENT_UPDATE, PUT, AUTHENTICATED_AND_OWNER),
  COMMENT_DELETE_ENDPOINT(COMMENT_BASE + COMMENT_DELETE, DELETE, ADMIN_OR_AUTHENTICATED_AND_OWNER),

  // Photo
  PHOTO_SAVE_AD_PHOTO_FILES_ENDPOINT(PHOTO_BASE + PHOTO_SAVE_AD_PHOTO_FILES, POST, AUTHENTICATED_AND_OWNER),
  PHOTO_DELETE_AD_PHOTOS_WITH_FILES_ENDPOINT(PHOTO_BASE + PHOTO_DELETE_AD_PHOTOS_WITH_FILES, DELETE, AUTHENTICATED_AND_OWNER),
  PHOTO_FIND_ALL_BY_ADID_ENDPOINT(PHOTO_BASE + PHOTO_FIND_ALL_BY_ADID, GET, PUBLIC),
  PHOTO_SAVE_USER_PHOTO_FILES_ENDPOINT(PHOTO_BASE + PHOTO_SAVE_USER_PHOTO_FILES, POST, AUTHENTICATED_AND_OWNER),
  PHOTO_DELETE_USER_PROFILE_PICTURE_ENDPOINT(PHOTO_BASE + PHOTO_DELETE_USER_PROFILE_PICTURE, DELETE, AUTHENTICATED_AND_OWNER),
  PHOTO_BY_USERID_ENDPOINT(PHOTO_BASE + PHOTO_BY_USERID, GET, PUBLIC),

  // Photo Files
  PHOTO_FILES_FIND_ALL_BY_ADID_ENDPOINT(PHOTO_FILES_BASE + PHOTO_FILES_FIND_ALL_BY_ADID, GET, PUBLIC),
  PHOTO_FILES_FIND_AD_PHOTO_FILE_BY_IDS_ENDPOINT(PHOTO_FILES_BASE + PHOTO_FILES_FIND_AD_PHOTO_FILE_BY_IDS, GET, PUBLIC),
  PHOTO_FILES_FIND_PROFILE_PICTURE_FILE_BY_USERID_ENDPOINT(PHOTO_FILES_BASE + PHOTO_FILES_FIND_PROFILE_PICTURE_FILE_BY_USERID, GET, PUBLIC),

  // Sample Data
  SAMPLE_DATA_ADD_ADS_ENDPOINT(SAMPLE_DATA_BASE + SAMPLE_DATA_ADD_ADS, POST, ADMIN_ONLY),

  // Tag
  TAG_GET_ALL_ENDPOINT(TAG_BASE + TAG_GET_ALL, GET, PUBLIC),
  TAG_GET_BY_ID_ENDPOINT(TAG_BASE + TAG_GET_BY_ID, GET, PUBLIC),
  TAG_CREATE_ENDPOINT(TAG_BASE + TAG_CREATE, POST, AUTHENTICATED),
  TAG_UPDATE_ENDPOINT(TAG_BASE + TAG_UPDATE, PUT, AUTHENTICATED_AND_OWNER),
  TAG_DELETE_ENDPOINT(TAG_BASE + TAG_DELETE, DELETE, ADMIN_OR_AUTHENTICATED_AND_OWNER),
  // User
  USER_GET_ALL_ENDPOINT(USER_BASE + USER_GET_ALL, GET, PUBLIC),
  USER_GET_BY_ID_ENDPOINT(USER_BASE + USER_GET_BY_ID, GET, PUBLIC),
  USER_FULL_GET_BY_ID_ENDPOINT(USER_BASE + USER_FULL_GET_BY_ID, GET, AUTHENTICATED),
  USER_GET_BY_EMAIL_ENDPOINT(USER_BASE + USER_GET_BY_EMAIL, GET, AUTHENTICATED),
  USER_UPDATE_ENDPOINT(USER_BASE + USER_UPDATE, PUT, AUTHENTICATED_AND_OWNER),
  USER_DELETE_ENDPOINT(USER_BASE + USER_DELETE, DELETE, ADMIN_OR_AUTHENTICATED_AND_OWNER);

  private final String path;
  private final HttpMethod method;
  private final AccessPolicy policy;

  //  private final boolean secured;
  //  private final boolean requiresOwnership;
  //  private final Set<String> requiredAuthorities;

  //  ApiEndpoint(String path, HttpMethod method, boolean secured) {
  ApiEndpoint(String path, HttpMethod method, AccessPolicy policy) {
    //  ApiEndpoint(String path, HttpMethod method, boolean secured, boolean ownership,Set<String>
    // requiredAuthorities) {
    this.path = path;
    this.method = method;
    this.policy = policy;
    //    this.secured = secured;
    //    this.requiresOwnership=ownership;
    //    this.requiredAuthorities = Set.copyOf(requiredAuthorities); // immutable copy
  }
}
